openapi: 3.0.0

info:
  title: Mujin Controller API
  version: v1
  description: "This is the main API for the Mujin Controller. \n\n ![](https://d33wubrfki0l68.cloudfront.net/a4d671d83f9e8d767d05b585e8d12ae906b7a3bd/0a691/wp-content/themes/mujin/assets/jp/img/logo.svg) \n\n

## Introduction

This API is based on the HTTP protocol and can be accessed at port `80` on the Mujin controller.
You can try these methods in a web browser. The web browser will prompt for username and password before allowing access. 
See the next section for details on how to authenticate when using this API.

## Authentication

To use this API, the client side software needs to use **Basic authentication** to authenticate with HTTP server on the controller. 
This can be done by supplying the following HTTP header to the request:
```
Authorization: Basic bXVqaW46bXVqaW4=
```
Where `bXVqaW46bXVqaW4=` is a base64 string, encoding the username and password separated by a `:`, in this case `mujin:mujin`.
"
  contact:
    name: Mujin Inc.
    email: info@mujin.co.jp
    url: 'https://www.mujin.co.jp'
  license:
    name: TBD
    url: 'https://www.mujin.co.jp'

servers:
- url: http://{controller}/
  description: The address of your Mujin controller. You need to specify the IP if DNS is not set up to resolve hostnames on the network. You can determine the IP address through the user interface on the controller.
  variables:
    controller:
      default: controller123

paths:
  "/systeminfo/":
    get:
      summary: Get System Info
      tags:
        - System
      description: This function retrieves the system information from the controller.
      responses:
        '200':
          description: A JSON containing the System Information.
          content:
            application/json:
              schema:
                type: object
                example:
                  hardware: HARDWARE-MODEL
                  product: PRODUCT-ID
                  id: controller
                properties:
                  hardware:
                    type: string
                  product:
                    type: string
                  id:
                    type: string
                required:
                - hardware
                - product
                - id
      operationId: GET_systeminfo
      parameters:
        - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/systemstats/":
    get:
      summary: Get System Stats
      tags:
        - System
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  memory:
                    type: object
                  disk:
                    type: object
                  temperature:
                    type: array
                    items:
                      type: object
                  cpu:
                    type: object
                required:
                - memory
                - disk
                - temperature
                - cpu
      operationId: GET_systemstats
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/interfaces/":
    get:
      summary: Get Interfaces
      tags:
        - System
      responses:
        '200':
          description: ''
      operationId: GET_interfaces
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/upgrade/":
    get:
      summary: Get Upgrade (???)
      tags:
        - System
      responses:
        '200':
          description: ''
      operationId: GET_upgrade
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      summary: Post Upgrade
      tags:
        - System
      responses:
        '200':
          description: ''
      operationId: POST_upgrade
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      summary: Delete Upgrade
      tags:
        - System
      responses:
        '200':
          description: ''
      operationId: DELETE_upgrade
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/reboot/":
    post:
      summary: Post Reboot
      tags: 
        - System
      responses:
        '200':
          description: ''
      operationId: POST_reboot
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/halt/":
    post:
      summary: Post Halt
      tags: 
        - System
      responses:
        '200':
          description: ''
      operationId: POST_halt
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/restartserver/":
    post:
      summary: Post Restart Server
      tags: 
        - System
      responses:
        '200':
          description: ''
      operationId: POST_restartserver
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/log/ordercycle/":
    get:
      summary: Get Ordercycle log
      tags: 
        - Logs
      responses:
        default:
          description: ''
      operationId: GET_log-ordercycle
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/log/plcsignal/":
    get:
      summary: Get PLC Signal log
      tags: 
        - Logs
      responses:
        default:
          description: ''
      operationId: GET_log-plcsignal
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/log/plcsignalanalysis/":
    get:
      summary: Get PLC Signal Analysis log
      tags: 
        - Logs
      responses:
        default:
          description: ''
      operationId: GET_log-plcsignalanalysis
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/log/user/{category}/":
    get:
      summary: Get User Category log
      tags: 
        - Logs
      responses:
        default:
          description: ''
      operationId: GET_log-user-category
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    parameters:
    - name: category
      in: path
      required: true
      schema:
        type: string
  "/config/":
    get:
      summary: Get Config
      tags: 
        - Config
      description: |-
        Retrieve configuration file content from the controller.
      responses:
        default:
          description: ''
      operationId: GET_config
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - name: filename
        in: path
        required: true
        description: (optional) The name of the config file. Can be either controllersystem.conf, binpickingsystem.conf, teachworkersystem.conf or robotbridges.conf.json.
        schema:
          type: string
          minimum: 1
        
    put:
      summary: Put Config
      tags: 
        - Config
      responses:
        default:
          description: ''
      operationId: PUT_config
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/signalmap/":
    get:
      summary: Get Signal Map
      tags: 
        - Config
      responses:
        default:
          description: ''
      operationId: GET_signalmap
  "/signalmap/{pk}/":
    get:
      summary: Get Signal Map (Primary Key)
      tags: 
        - Config
      responses:
        default:
          description: ''
      operationId: GET_signalmap-pk
    put:
      summary: Put Signal Map (Primary Key)
      tags: 
        - Config
      responses:
        default:
          description: ''
      operationId: PUT_signalmap-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      summary: Delete Signal Map (Primary Key)
      tags: 
        - Config
      responses:
        default:
          description: ''
      operationId: DELETE_signalmap-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/backup/":
    get:
      summary: Get Backup
      tags: 
        - System
      responses:
        default:
          description: ''
      operationId: GET_backup
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      summary: Post Backup
      tags: 
        - System
      responses:
        default:
          description: ''
      operationId: POST_backup
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/query/barcodes/":
    get:
      summary: Get Query Barcodes
      tags: 
        - Barcodes
      description: |-
        Query a list of scenepks based on the barcode field
      responses:
        default:
          description: ''
      operationId: GET_query-barcodes
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/referenceobjectpks/":
    post:
      summary: Post Reference Object PKs
      tags: 
        - Objects
      description: |-
        Add reference object Primary Keys to the scene.
      responses:
        default:
          description: ''
      operationId: POST_referenceobjectpks
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/file/upload/":
    post:
      summary: Post File (Upload)
      tags: 
        - Files
      description: |-
        Upload a file.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                  modified:
                    type: number
                  size:
                    type: integer
                required:
                - filename
                - modified
                - size
      operationId: POST_file-upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                filename:
                  type: string
                file:
                  type: string
              required:
              - file
              type: object
        required: true
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
      - name: filename
        in: query
        schema:
          type: string
  "/file/delete/":
    post:
      summary: (Post) Delete File
      tags: 
        - Files
      description: |-
        Delete a file from the controller.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                required:
                - filename
      operationId: POST_file-delete
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
      - name: filename
        in: query
        required: true
        schema:
          type: string
  "/file/list/":
    get:
      summary: (Get) List of Files
      tags: 
        - Files
      description: |-
        Get a list of files on the controller.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  filename1.mujin.dae:
                    modified: 1565932929.9884703
                    size: 9938
                type: object
                properties:
                  filename:
                    type: object
                    properties:
                      modified:
                        type: number
                      size:
                        type: integer
                    required:
                    - modified
                    - size
      operationId: GET_file-list
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/file/download/":
    get:
      summary: Get File
      tags: 
        - Files
      description: |-
        Download a file from the controller.
      responses:
        '302':
          description: ''
      operationId: GET_file-download
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - name: filename
        in: query
        required: true
        schema:
          type: string
    head:
      summary: (Head) Get File information
      tags: 
        - Files
      description: |-
        Get the metadata of a file.
      responses:
        '302':
          description: ''
      operationId: HEAD_file-download
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - name: filename
        in: query
        required: true
        schema:
          type: string
  "/api/v1/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/api/v1/debug/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  objects:
                  - description: System logs
                    name: system-logs
                    downloadUri: "/api/v1/debug/system-logs/download/"
                    pk: system-logs
                    resource_uri: "/api/v1/debug/system-logs/"
                    datemodified: '2020-03-19T15:07:42.633247+09:00'
                    size: 125289232
                  meta:
                    total_count: 1
                    previous:
                    limit: 20
                    offset: 0
                    next:
                type: object
                properties:
                  objects:
                    type: array
                    items:
                      "$ref": "#/components/schemas/DebugResource"
                  meta:
                    "$ref": "#/components/schemas/Meta"
                required:
                - objects
                - meta
      operationId: GET_api-v1-debug
  "/api/v1/debug/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                description: System logs
                name: system-logs
                downloadUri: "/api/v1/debug/system-logs/download/"
                pk: system-logs
                resource_uri: "/api/v1/debug/system-logs/"
                datemodified: '2020-03-19T15:07:42.633247+09:00'
                size: 125289232
              schema:
                "$ref": "#/components/schemas/DebugResource"
      operationId: GET_api-v1-debug-pk
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/profile/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-profile
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
  "/api/v1/ui/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-ui
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: POST_api-v1-ui
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/task/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-task
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-task
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/task/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-task-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-task-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-task-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/job/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-job
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-job
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/job/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-job-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-job-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-job-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/planningresult/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-planningresult
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-planningresult
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/planningresult/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-planningresult-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-planningresult-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-planningresult-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/binpickingresult/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-binpickingresult
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-binpickingresult
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/binpickingresult/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-binpickingresult-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-binpickingresult-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-binpickingresult-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/controllerState/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-controllerState
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-controllerState
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/controllerState/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-controllerState-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-controllerState-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-controllerState-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/cycleLog/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-cycleLog
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-cycleLog
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/cycleLog/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-cycleLog-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-cycleLog-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-cycleLog-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/itl/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-itl
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-itl
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/itl/{pk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-itl-pk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-itl-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-itl-pk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: pk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/scene/":
    get:
      summary: Get scenes
      description: Lists the scenes on the controller.
      tags: 
        - Scenes
      responses:
        '200':
          description: The requested scenes.
          content:
            application/json:
              schema:
                description: An array of the scenes, plus metadata.
                type: object
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta'
                  objects:
                    type: array
                    items:
                      $ref: '#/components/schemas/Scene'
      operationId: GET_api-v1-scene
      parameters:
        - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      tags: 
        - Scenes
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-scene
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/scene/{scenepk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-scene-scenepk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-scene-scenepk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-scene-scenepk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: scenepk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/scene/{scenepk}/instobject/":
    get:
      summary: Get all instobjects
      description: Gets an array of all instobjects in the scene.
      tags: 
        - Objects
      responses:
        '200':
          description: A list of the instobjects in the scene.
          content:
            application/json:
              schema:
                description: An array of the instobjects in the scene, plus metadata.
                type: object
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta'
                  objects:
                    type: array
                    items:
                      $ref: '#/components/schemas/instobject'
      operationId: GET_api-v1-scene-scenepk-instobject
      parameters:
        - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      summary: Create instobject
      description: Create a new instance of an object. If only a name is supplied, this also creates a new object that is linked to the instobject. The newly created object has no geometry. Add geometry to the object using the objectpk. (TODO; Link the path to do this)
      tags: 
        - Objects
      responses:
        '201':
          description: The instobject data
          content:
            application/json:
              schema:
                type: object
              # schema:
              #   $ref: "#/components/schemas/instobject"
      operationId: POST_api-v1-scene-scenepk-instobject
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new instobject's name
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: scenepk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/scene/{scenepk}/instobject/{instobjectpk}/":
    get:
      summary: Get instobject
      description: Get an instobject
      tags: 
        - Objects
      responses:
        '200':
          description: The requested instobject.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/instobject"
      operationId: GET_api-v1-scene-scenepk-instobject-instobjectpk
      parameters:
        - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    post:
      summary: Create instobject (??)
      description: Create a new instance of an object. If only a name is supplied, this also creates a new object that is linked to the instobject. The newly created object has no geometry. Add geometry to the object using the objectpk. (TODO; Link the path to do this)
      tags: 
        - Objects
      responses:
        '201':
          description: The newly created instobject.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/instobject"
      operationId: POST_api-v1-scene-scenepk-instobject-instobjectpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      summary: Delete instobject
      description: Delete an object instance.
      tags: 
        - Objects
      responses:
        '204':
          description: OK. The instobject was deleted.
      operationId: DELETE_api-v1-scene-scenepk-instobject-instobjectpk
      parameters:
      - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: scenepk
      in: path
      required: true
      schema:
        type: string
    - name: instobjectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/scene/{scenepk}/instobject/{instobjectpk}/tool/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-scene-scenepk-instobject-instobjectpk-tool
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-scene-scenepk-instobject-instobjectpk-tool
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: scenepk
      in: path
      required: true
      schema:
        type: string
    - name: instobjectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/scene/{scenepk}/instobject/{instobjectpk}/tool/{toolpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-scene-scenepk-instobject-instobjectpk-tool-toolpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-scene-scenepk-instobject-instobjectpk-tool-toolpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-scene-scenepk-instobject-instobjectpk-tool-toolpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: toolpk
      in: path
      required: true
      schema:
        type: string
    - name: scenepk
      in: path
      required: true
      schema:
        type: string
    - name: instobjectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/":
    get:
      summary: Get Object (PK)
      description: Gets an object from the scene by referencing its primary key. The primary key is a unique identifier (in the parent namespace).
      tags: 
        - Objects
      responses:
        '200':
          description: The object description in JSON format. See [this link (TODO)](mujin-data-types.md) for more information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenraveObject'
      operationId: GET_api-v1-object-objectpk
      parameters:
        - "$ref": "#/components/parameters/trait_basicAuth_Authorization"
    put:
      summary: Put Object (PK)
      description: Sets an object in the scene by referencing its primary key. The primary key is a unique identifier (in the parent namespace).
      tags: 
        - Objects
      responses:
        '201':
          description: OK. The object was set successfully.
      operationId: PUT_api-v1-object-objectpk
      requestBody:
        description: The object description in JSON format. See [this link (TODO)](mujin-data-types.md) for more information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenraveObject'
      parameters:
        - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
        - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      summary: Delete Object (PK)
      description: Deletes an object from the scene by referencing its primary key. The primary key is a unique identifier (in the parent namespace).
      tags: 
        - Objects
      responses:
        '204':
          description: OK. The object was deleted.
      operationId: DELETE_api-v1-object-objectpk
      parameters:
        - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
        - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      description: The primary key of the object. 
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/link/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-link
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-object-objectpk-link
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/link/{linkpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-link-linkpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-object-objectpk-link-linkpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-object-objectpk-link-linkpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: linkpk
      in: path
      required: true
      schema:
        type: string
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/attachment/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-attachment
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-object-objectpk-attachment
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/attachment/{attachmentpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-attachment-attachmentpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-object-objectpk-attachment-attachmentpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-object-objectpk-attachment-attachmentpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: attachmentpk
      in: path
      required: true
      schema:
        type: string
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/geometry/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-geometry
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-object-objectpk-geometry
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/geometry/{geometrypk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-geometry-geometrypk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-object-objectpk-geometry-geometrypk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-object-objectpk-geometry-geometrypk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: geometrypk
      in: path
      required: true
      schema:
        type: string
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/ikparam/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-ikparam
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-object-objectpk-ikparam
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/ikparam/{ikparampk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-ikparam-ikparampk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-object-objectpk-ikparam-ikparampk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-object-objectpk-ikparam-ikparampk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: ikparampk
      in: path
      required: true
      schema:
        type: string
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/graspset/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-graspset
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-object-objectpk-graspset
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/object/{objectpk}/graspset/{graspsetpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-object-objectpk-graspset-graspsetpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-object-objectpk-graspset-graspsetpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-object-objectpk-graspset-graspsetpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: graspsetpk
      in: path
      required: true
      schema:
        type: string
    - name: objectpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/robot/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-robot
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
  "/api/v1/robot/{robotpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot-robotpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-robot-robotpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-robot-robotpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: robotpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/robot/{robotpk}/tool/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot-robotpk-tool
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-robot-robotpk-tool
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: robotpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/robot/{robotpk}/tool/{toolpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot-robotpk-tool-toolpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-robot-robotpk-tool-toolpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-robot-robotpk-tool-toolpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: toolpk
      in: path
      required: true
      schema:
        type: string
    - name: robotpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/robot/{robotpk}/attachedsensor/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot-robotpk-attachedsensor
    post:
      tags: 
        - Unsorted (ToDo)
      responses:
        '201':
          description: ''
      operationId: POST_api-v1-robot-robotpk-attachedsensor
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: robotpk
      in: path
      required: true
      schema:
        type: string
  "/api/v1/robot/{robotpk}/attachedsensor/{attachedsensorpk}/":
    get:
      tags: 
        - Unsorted (ToDo)
      responses:
        '200':
          description: ''
      operationId: GET_api-v1-robot-robotpk-attachedsensor-attachedsensorpk
    put:
      tags: 
        - Unsorted (ToDo)
      responses:
        '202':
          description: ''
      operationId: PUT_api-v1-robot-robotpk-attachedsensor-attachedsensorpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    delete:
      tags: 
        - Unsorted (ToDo)
      responses:
        '204':
          description: ''
      operationId: DELETE_api-v1-robot-robotpk-attachedsensor-attachedsensorpk
      parameters:
      - "$ref": "#/components/parameters/trait_csrfToken_X-CSRFToken"
      - "$ref": "#/components/parameters/trait_csrfToken_Cookie"
    parameters:
    - name: attachedsensorpk
      in: path
      required: true
      schema:
        type: string
    - name: robotpk
      in: path
      required: true
      schema:
        type: string

components:
  schemas:
    translate:
      description: The translation in xyz format.
      type: array
      minLength: 3
      maxLength: 3
      items:
        type: number
    quaternion:
      description: The rotation as a quaternion in wxyz format.
      type: array
      minLength: 4
      maxLength: 4
      items:
        type: number
    Meta:
      type: object
      properties:
        total_count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        previous:
          type: string
          nullable: true
        next:
          type: string
          nullable: true
    DebugResource:
      type: object
      properties:
        pk:
          type: string
        resource_uri:
          type: string
        description:
          type: string
        name:
          type: string
        downloadUri:
          type: string
        datemodified:
          type: string
        size:
          type: integer
      required:
      - pk
      - resource_uri
      - description
      - name
      - downloadUri
      - datemodified
      - size
    OpenraveObject:
      type: object
      example:
        mesh: (stl data)
      properties:
        mesh:
          type: string
      required:
      - mesh
    instobject:
      type: object
      description: An object instance in a scene.
      example:
        links: {...}
        name: sourceconveyor_left
        object_pk: itodenki_sg6-ft-s-c6.mujin.msgpack%40body9_motion
        pk: body9_motion
        quaternion: [1,0,0,0]
        translate: [0,0,0]
        unit: mm
        reference_uri: mujin:/itodenki_sg6-ft-s-c6.mujin.msgpack@body9_motion
      properties:
        name:
          type: string
          description: The name of the object instance. This is *not* the identifier and is not unique. Multiple objects can have the same name.
        links:
          type: array
          description: A list of OpenRAVE links
          items:
            # type: object
            # description: OpenRAVE links
            $ref: "#/components/schemas/Link"
        object_pk:
          type: string
        pk:
          type: string
        quaternion:
          $ref: '#/components/schemas/quaternion'
        translate:
          $ref: '#/components/schemas/translate'
        reference_uri:
          type: string
        unit:
          type: string
          example: mm
        attachedsensors:
          type: array
          items:
            $ref: '#/components/schemas/AttachedSensor'
        dofvalues:
          type: array
          description: The joint values of this robot/gripper/object. 
          items:
            type: number
        insttools:
          type: array
          description: The tool instances of a robot.
          items:
            $ref: '#/components/schemas/insttool'
        connectedBodies:
          type: array
          description: A list of (the names of) connected bodies.
          items:
            type: object
            properties:
              name:
                description: The name of the connected body.
                type: string
    Scene:
      type: object
      description: An OpenRAVE scene. This data structure contains objects, sensors, robots, manipulators, joint states and more. It describes our robot and its physical environment.
      example:
        aabb_half_extents: [0, 0, 0]
        barcodeScanningGain: 1
        barcodes: []
        contentdatemodified: "2021-11-26T14:24:11.193685+09:00"
        datemodified: "2021-11-26T14:24:11.193685+09:00"
        disabledReferenceObjectPks: []
        gripperperformances: []
        keywords: scene
        mass: 0
        materialType: 
        name: itodenki_sg6-ft-s-c6
        note: 
        objectPackingId: 254
        objectType: 
        pk: itodenki_sg6-ft-s-c6.mujin.msgpack
        referenceobjectpks: []
        scenetype: mujinmsgpack
        transferSpeedMult: 1
        upaxis: Z_UP
        uri: mujin:/itodenki_sg6-ft-s-c6.mujin.msgpack
      properties:
        aabb_half_extents: 
          type: array
          items:
            type: number
          minLength: 3
          maxLength: 3
        barcodeScanningGain:
          type: number
        barcodes:
          type: array
          items:
            type: number
        contentdatemodified:
          type: string
          description: A date string.
          example: "2021-11-26T14:24:11.193685+09:00"
        datemodified: 
          type: string
          description: A date string.
          example: "2021-11-26T14:24:11.193685+09:00"
        disabledReferenceObjectPks:
          type: array
          items:
            type: string
        gripperperformances:
          type: array
          items:
            type: string
          description: "???"
        keywords: 
          type: string
          example: scene
        mass:
          type: number
        materialType: 
          type: string
        name: 
          type: string
        note: 
          type: string
        objectPackingId:
          type: integer
        objectType: 
          type: string
        pk: 
          type: string
        referenceobjectpks:
          type: array
          items:
            type: string
        scenetype:
          type: string
          example: mujinmsgpack
        transferSpeedMult:
          type: number
        upaxis: 
          type: string
          example: Z_UP
        uri: 
          type: string
          example: mujin:/itodenki_sg6-ft-s-c6.mujin.msgpack
    Link:
      type: object
      description: An OpenRAVE scene. This data structure contains objects, sensors, robots, manipulators, joint states and more. It describes our robot and its physical environment.
      example:
        collision: true
        linkpk: link0
        name: base
        quaternion: [1, 0, 0, 0 ]
        translate: [1159, 1340, 500 ]
        visible: true
      properties:
        collision:
          type: boolean
        visible:
          type: boolean
        linkpk:
          type: string
        name:
          type: string
        quaternion:
          $ref: '#/components/schemas/quaternion'
        translate:
          $ref: '#/components/schemas/translate'
    AttachedSensor:
      type: object
      description: The position of a sensor in an OpenRAVE scene. This data structure contains the sensor name and its translation and quaternion.
      example:
        name: ensenso_l_raw
        quaternion: [-0.05, 0.7, 0.71, -0.018]
        translate: [1159, 1340, 500]
      properties:
        name:
          type: string
          description: The name of the sensor.
        quaternion:
          $ref: '#/components/schemas/quaternion'
        translate:
          $ref: '#/components/schemas/translate'
    insttool:
      type: object
      description: An instance of a tool.
      example:
        quaternion: [0.0012217, 0.000003625, 0.9999, -0.002967]
        translate: [344, 0.5, 754]
        direction: [0, 0, 1]
        name: suction0
      properties:
        name:
          type: string
          description: The name of the sensor.
        quaternion:
          $ref: '#/components/schemas/quaternion'
        translate:
          $ref: '#/components/schemas/translate'
        direction:
          description: The "direction" of a tool, defined as a vector in the coordinate system. For example, this would point away from the center of a suction cup.
          type: array
          minLength: 3
          maxLength: 3
          items:
            type: number
  responses: {}
  parameters:
    trait_basicAuth_Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
    trait_csrfToken_X-CSRFToken:
      name: X-CSRFToken
      in: header
      required: true
      schema:
        type: string
    trait_csrfToken_Cookie:
      name: Cookie
      in: header
      required: true
      schema:
        type: string
    scenepk:
      name: scenepk
      in: path
      schema:
        type: string
      example: myscene.mujin.msgpack
      required: true
      description: The scene's primary key.
    instobjectpk:
      name: instobjectpk
      in: path
      schema:
        type: string
      example: body1
      required: true
      description: The primary key of the instobject, without the name of the scene it is a child of. An object_pk may be of the format '{scenename}%40{instobjectok}''. This instobjectpk is the latter part of that object_pk. It is a unique identifier inside the scene.
    objectpk:
      name: objectpk
      in: path
      schema:
        type: string
      example: scenename%40body1
      required: true
      description: The object's primary key. Includes the name of the scene it is a child of. The object_pk may be of the format '{scenename}%40{instobjectok}.' It is unique to this object.
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
